### ISSUE TITLE
CSS Refactoring

### ISSUE THREAD

**Issue by zimmi88** [linkedin/hopscotch#290]
Evaluate our current CSS and see if there's anything to clean up or refactor.

Issues rolled into this ticket
-----------------------------------
- [ ] #279 Firefox: Bubble arrow shifted 1px
- [ ] #276 Various CSS improvements
- [ ] #272 RTL support
- [ ] #270 Arrow is blocking interaction with element being pointed at.
- [ ] Make it easier to update look and feel using vars. (Previously reported as #117)
- [ ] Choreograph an animation solution that doesn't require the JS to have any knowledge of the animation timing. (Previously discussed on #200)
- [ ] Don't rely on sprite for look and feel.
- [ ] Find a way to separate core styles from theming. (Such that core styles can be included with any theme-specific styles so it's easier to adapt the bubble theme to mesh with whichever site it's included with).
